output   = "internal/app/dbmodels"
wipe     = true
no-tests = true

[psql]
  dbname = "postgres"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = "mysecretpassword"
  schema = "public"
  sslmode = "disable"
  blacklist = ["goose_db_version"]

[[types]]
  [types.match]
    type = "int64"
    nullable = false
  [types.replace]
    type = "int32"
[[types]]
  [types.match]
    type = "null.Int64"
    nullable = true
  [types.replace]
    type = "null.Int32"
