// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Agent         string
	Command       string
	GroupLogs     string
	GroupsPage    string
	Projects      string
	RunReport     string
	Runs          string
	Scenarios     string
	Scripts       string
	SimpleScripts string
	Statistic     string
	StatisticDump string
	Traces        string
}{
	Agent:         "agent",
	Command:       "command",
	GroupLogs:     "group_logs",
	GroupsPage:    "groups_page",
	Projects:      "projects",
	RunReport:     "run_report",
	Runs:          "runs",
	Scenarios:     "scenarios",
	Scripts:       "scripts",
	SimpleScripts: "simple_scripts",
	Statistic:     "statistic",
	StatisticDump: "statistic_dump",
	Traces:        "traces",
}
